# ==============================================================================
# Rhinella spinulosa skin microbiota
# Main figure generation — version 2
# ==============================================================================
# This script does not perform the statistical analyses. It loads the workspace
# generated by Rhinella_spinulosa_microbiota_pipeline_v2.R and reproduces the
# manuscript main figures.
#
# It has not been executed in the current environment because R is unavailable.
# ==============================================================================

DATA_DIR <- "data"
RESULTS_DIR <- "results"
FIGURES_DIR <- "figures"

if (!dir.exists(FIGURES_DIR)) dir.create(FIGURES_DIR, recursive = TRUE)

load(file.path(RESULTS_DIR, "analysis_workspace.RData"))

suppressPackageStartupMessages({
  library(ggplot2)
  library(tidyverse)
  library(ggpubr)
  library(patchwork)
  library(ggraph)
  library(graphlayouts)
  library(tidytext)
  library(cowplot)
  library(ggalluvial)
  library(igraph)
  library(grid)
})

# ---- Figure 1: Host filtering -----------------------------------------------

##FIGURE 1: Host filtering
category_colors <- c(
  "Water only"               = "#41AE76",
  "Shared (non-core)"        = "#2C7FB8",
  "Skin only (non-core)"     = "#74A9CF",
  "Core (shared)"              = "#FDB863",
  "Core (skin-restricted)"     = "#CC4C02"
)

#panel A
panelA <- asv_master %>%
  count(Category) %>%
  mutate(
    Category = recode(
      Category,
      Water_only = "Water only",
      Shared_non_core = "Shared (non-core)",
      Skin_only_non_core = "Skin only (non-core)",
      Core_detected_in_water = "Core (shared)",
      Core_not_detected_in_water = "Core (skin-restricted)"
    ),
    Category = factor(
      Category,
      levels = c(
        "Water only",
        "Shared (non-core)",
        "Skin only (non-core)",
        "Core (shared)",
        "Core (skin-restricted)"
      )
    )
  )

ggplot(panelA,
       aes(Category, n, fill = Category)) +
  
  geom_col(width = 0.50) +
  
  geom_text(
    aes(label = n),
    vjust = -0.35,
    fontface = "bold",
    size = 5
  ) +
  
  scale_fill_manual(values = category_colors) +
  
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))
  ) +
  
  labs(
    x = NULL,
    y = "Number of ASVs"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      face = "bold",
      size = 13
    ),
    axis.title.y = element_text(
      face = "bold"
    )
  )

#panel B
plot_df <- asv_master %>%
  
  mutate(
    
    RelativeAbundance = case_when(
      
      Category == "Water_only" ~ MeanRel_water,
      
      TRUE ~ MeanRel_skin
      
    ),
    
    Genus = ifelse(
      is.na(Genus) | Genus == "",
      "Unclassified",
      Genus
    )
    
  )

plot_df <- plot_df %>%
  mutate(
    Genus = as.character(Genus),
    Genus = str_trim(Genus),
    Genus = str_replace_all(Genus, "_", " "),
    Genus = ifelse(
      is.na(Genus) | Genus == "",
      "Unclassified",
      Genus
    )
  )

plot_df <- plot_df %>%
  
  filter(
    
    Genus!="Unclassified"
    
  )

plot_df <- plot_df %>%
  
  filter(
    
    Genus!="Uncultured"
    
  )

plot_df <- plot_df %>%
  
  filter(
    
    Genus!="uncultured"
    
  )

genus_abundance <- plot_df %>%
  
  group_by(Category, Genus) %>%
  
  summarise(
    
    RelativeAbundance = sum(RelativeAbundance),
    
    .groups = "drop"
    
  )

top15 <- genus_abundance %>%
  
  group_by(Category) %>%
  
  arrange(
    
    desc(RelativeAbundance),
    
    .by_group = TRUE
    
  ) %>%
  
  slice_head(n = 15) %>%
  
  ungroup()

top15$Category <- recode(
  
  top15$Category,
  
  Water_only = "Water only",
  
  Shared_non_core = "Shared (non-core)",
  
  Skin_only_non_core = "Skin only (non-core)",
  
  Core_detected_in_water = "Core (shared)",
  
  Core_not_detected_in_water = "Core (skin-restricted)"
  
)

top15 <- top15 %>%
  
  mutate(
    
    Genus = reorder_within(
      
      Genus,
      
      RelativeAbundance,
      
      Category
      
    )
    
  )

ggplot(
  
  top15,
  
  aes(
    
    Genus,
    
    RelativeAbundance*100,
    
    fill=Category
    
  )
  
)+
  
  geom_col(width=.75)+
  
  coord_flip()+
  
  facet_wrap(
    
    ~Category,
    
    nrow=1,
    
    scales="free_x"
    
  )+
  geom_text(
    
    aes(
      
      label = ifelse(
        
        RelativeAbundance*100 > 5,
        
        round(RelativeAbundance*100,1),
        
        ""
        
      )
      
    ),
    
    hjust=-0.15,
    
    size=3
    
  )+
  
  scale_x_reordered()+
  
  scale_fill_manual(
    
    values=category_colors
    
  )+
  
  labs(
    
    x=NULL,
    
    y="Relative abundance (%)"
    
  )+
  
  theme_classic(base_size=13)+
  
  theme(
    
    legend.position="none",
    
    panel.grid=element_blank(),
    
    strip.background=element_blank(),
    
    strip.text=element_text(
      
      face="bold",
      
      size=13
      
    ),
    
    axis.text.y=element_text(
      
      size=10
      
    ),
    
    axis.title.y=element_blank(),
    
    axis.title.x=element_text(
      
      face="bold"
      
    )
    
  )


# ---- Figure 2: Network reorganization and topological trajectories -----------

#######plots estadisticos redes postmetamorficas#######
############################################################
plot_spearman <- function(
    data,
    x,
    y,
    rho,
    pvalue,
    ylab){
  
  ggplot(
    data,
    aes_string(
      x=x,
      y=y
    )
  )+
    
    geom_point(
      alpha=.5,
      color="grey40",
      size=1.8
    )+
    
    geom_smooth(
      method="loess",
      color="#1F78B4",
      fill="#A6CEE3",
      linewidth=1
    )+
    
    annotate(
      
      "text",
      
      x=min(data[[x]],na.rm=TRUE),
      
      y=max(data[[y]],na.rm=TRUE),
      
      hjust=0,
      
      label=paste0(
        "\u03C1 = ",
        round(rho,3),
        "\nP < 0.001"
      ),
      
      fontface="bold",
      
      size=5
      
    )+
    
    labs(
      
      x="log10 Mean relative abundance",
      
      y=ylab
      
    )+
    
    theme_classic(base_size=14)
  
}

A <- plot_spearman(
  YL_mods,
  "log10MeanRel",
  "Degree",
  -.267,
  "<0.001",
  "Degree"
)

B <- plot_spearman(
  YL_mods,
  "log10MeanRel",
  "BetweennessCentrality",
  0.361,
  "<0.001",
  "BetweennessCentrality"
)

E <- plot_spearman(
  PAR_mods,
  "log10MeanRel",
  "Degree",
  -.483,
  "<0.001",
  "Degree"
)

F <- plot_spearman(
  PAR_mods,
  "log10MeanRel",
  "BetweennessCentrality",
  0.579,
  "<0.001",
  "BetweennessCentrality"
)

hub_prop <- function(
    data,
    hub_col,
    module_col){
  
  data %>%
    
    group_by(
      .data[[module_col]]
    ) %>%
    
    summarise(
      
      Nodes=n(),
      
      Hubs=sum(
        .data[[hub_col]]
      ),
      
      PropHub=100*Hubs/Nodes
      
    ) %>%
    
    arrange(
      desc(PropHub)
    )
  
}

degYL <- hub_prop(
  YL_mods,
  "Hub_degree",
  "X__glayCluster"
)

C = ggplot(
  
  degYL,
  
  aes(
    
    reorder(
      X__glayCluster,
      PropHub
    ),
    
    PropHub,
    
    fill=factor(
      X__glayCluster
    )
    
  )
  
)+
  
  geom_col()+
  
  geom_text(
    
    aes(
      
      label=paste0(
        
        round(
          PropHub,
          1
        ),
        
        "%\n(n=",
        
        Hubs,
        
        ")"
        
      )
      
    ),
    
    vjust=-.3,
    
    size=4
    
  )+
  
  theme_classic()+
  
  theme(
    
    legend.position="none"
    
  )

btwYL <- hub_prop(
  YL_mods,
  "Hub_between",
  "X__glayCluster"
)

D = ggplot(
  
  btwYL,
  
  aes(
    
    reorder(
      X__glayCluster,
      PropHub
    ),
    
    PropHub,
    
    fill=factor(
      X__glayCluster
    )
    
  )
  
)+
  
  geom_col()+
  
  geom_text(
    
    aes(
      
      label=paste0(
        
        round(
          PropHub,
          1
        ),
        
        "%\n(n=",
        
        Hubs,
        
        ")"
        
      )
      
    ),
    
    vjust=-.3,
    
    size=4
    
  )+
  
  theme_classic()+
  
  theme(
    
    legend.position="none"
    
  )

degPAR <- hub_prop(
  PAR_mods,
  "Hub_degree",
  "X__glayCluster"
)

G = ggplot(
  
  degPAR,
  
  aes(
    
    reorder(
      X__glayCluster,
      PropHub
    ),
    
    PropHub,
    
    fill=factor(
      X__glayCluster
    )
    
  )
  
)+
  
  geom_col()+
  
  geom_text(
    
    aes(
      
      label=paste0(
        
        round(
          PropHub,
          1
        ),
        
        "%\n(n=",
        
        Hubs,
        
        ")"
        
      )
      
    ),
    
    vjust=-.3,
    
    size=4
    
  )+
  
  theme_classic()+
  
  theme(
    
    legend.position="none"
    
  )

btwPAR <- hub_prop(
  PAR_mods,
  "Hub_between",
  "X__glayCluster"
)

H = ggplot(
  
  btwPAR,
  
  aes(
    
    reorder(
      X__glayCluster,
      PropHub
    ),
    
    PropHub,
    
    fill=factor(
      X__glayCluster
    )
    
  )
  
)+
  
  geom_col()+
  
  geom_text(
    
    aes(
      
      label=paste0(
        
        round(
          PropHub,
          1
        ),
        
        "%\n(n=",
        
        Hubs,
        
        ")"
        
      )
      
    ),
    
    vjust=-.3,
    
    size=4
    
  )+
  
  theme_classic()+
  
  theme(
    
    legend.position="none"
    
  )

theme_fig <- theme_classic(base_size = 18) +
  
  theme(
    
    axis.title = element_text(
      face = "bold",
      size = 18
    ),
    
    axis.text = element_text(
      size = 14,
      colour = "black"
    ),
    
    plot.title = element_text(
      face = "bold",
      size = 18,
      hjust = 0.5
    ),
    
    legend.position = "none",
    
    plot.margin =
      margin(6,6,6,6)
    
  )

A = A + theme_fig
B = B + theme_fig
C = C + theme_fig
D = D + theme_fig
E = E + theme_fig
F = F + theme_fig
G = G + theme_fig
H = H + theme_fig

pdf("FigureS3.pdf", height = 22, width = 36)
((A | B | C | D) /
    (E | F | G | H)) +
  
  plot_annotation(
    
    tag_levels = "A",
    
    theme = theme(
      
      plot.tag = element_text(
        size = 22,
        face = "bold"
      )
      
    )
    
  )
dev.off()


# ---- Figure 2D: Persistent-lineage topological trajectories ------------------

###Figura de trayectorias topológicas####
#######Figura 3D#####
get_role <- function(hub_degree, hub_btw){
  
  case_when(
    
    is.na(hub_degree) ~ NA_character_,
    
    hub_degree & hub_btw ~ "Both",
    
    hub_degree ~ "Degree",
    
    hub_btw ~ "BTW",
    
    TRUE ~ "None"
    
  )
  
}

alluvial_df <-
  
  persistent_ASVs %>%
  
  filter(
    Pattern == "LJA"
  ) %>%
  
  mutate(
    
    Larva_role = get_role(
      HubDegree_L,
      HubBTW_L
    ),
    
    Juvenile_role = get_role(
      HubDegree_J,
      HubBTW_J
    ),
    
    Adult_role = get_role(
      HubDegree_A,
      HubBTW_A
    )
    
  ) %>%
  
  select(
    
    Larva_ID,
    Post_ID,
    
    Larva_role,
    Juvenile_role,
    Adult_role
    
  )

alluvial_df <-
  
  alluvial_df %>%
  
  mutate(
    
    Trajectory = paste(
      Larva_role,
      Juvenile_role,
      Adult_role,
      sep = " → "
    )
    
  )

alluvial_plot <-
  
  alluvial_df %>%
  
  mutate(
    
    Larva_role = factor(
      Larva_role,
      levels = c("None","Degree","BTW","Both")
    ),
    
    Juvenile_role = factor(
      Juvenile_role,
      levels = c("None","Degree","BTW","Both")
    ),
    
    Adult_role = factor(
      Adult_role,
      levels = c("None","Degree","BTW","Both")
    )
    
  ) %>%
  
  count(
    
    Larva_role,
    Juvenile_role,
    Adult_role,
    
    name = "n"
    
  )

alluvial_plot <- alluvial_plot %>%
  mutate(
    Trajectory_type = case_when(
      
      Larva_role == "None" &
        Juvenile_role == "None" &
        Adult_role == "None" ~
        "Always peripheral",
      
      Larva_role == "Degree" |
        Juvenile_role == "Degree" |
        Adult_role == "Degree" ~
        "Degree trajectory",
      
      Larva_role == "BTW" |
        Juvenile_role == "BTW" |
        Adult_role == "BTW" ~
        "Betweenness trajectory",
      
      TRUE ~
        "Other"
      
    )
  )

alluvial_df <-
  
  alluvial_df %>%
  
  mutate(
    
    Trajectory = paste(
      Larva_role,
      Juvenile_role,
      Adult_role,
      sep = " → "
    )
    
  )

## Construir tabla de frecuencias
traj_df <-
  alluvial_df %>%
  count(Trajectory, name = "N") %>%
  arrange(desc(N))

## Ordenar el eje Y
traj_df$Trajectory <-
  factor(
    traj_df$Trajectory,
    levels = rev(traj_df$Trajectory)
  )

## Barplot
traj_df <-
  
  traj_df %>%
  
  mutate(
    
    Group = case_when(
      
      Trajectory == "None → None → None" ~
        "Always peripheral",
      
      grepl("Degree", Trajectory) ~
        "Degree trajectories",
      
      grepl("BTW", Trajectory) ~
        "Betweenness trajectories"
      
    )
    
  )

traj_df$Trajectory <-
  
  factor(
    
    traj_df$Trajectory,
    
    levels = c(
      
      "None → None → None",
      
      "Degree → None → None",
      "None → None → Degree",
      
      "BTW → None → None",
      "None → BTW → None",
      "None → None → BTW",
      "None → BTW → BTW"
      
    )
    
  )

traj_df$Trajectory <- factor(
  
  traj_df$Trajectory,
  
  levels = c(
    
    "None → None → None",
    
    "Degree → None → None",
    "None → None → Degree",
    
    "BTW → None → None",
    "None → BTW → None",
    "None → None → BTW",
    "None → BTW → BTW"
    
  )
  
)

traj_df$Group <- factor(
  
  traj_df$Group,
  
  levels = c(
    
    "Always peripheral",
    "Degree trajectories",
    "Betweenness trajectories"
    
  ),
  
  labels = c(
    
    "Always peripheral",
    "Degree-associated",
    "Betweenness-associated"
    
  )
  
)

traj_df$Trajectory <- factor(
  
  traj_df$Trajectory,
  
  levels = rev(c(
    
    "None → None → None",
    
    "Degree → None → None",
    "None → None → Degree",
    
    "BTW → None → None",
    "None → BTW → None",
    "None → None → BTW",
    "None → BTW → BTW"
    
  ))
  
)
LJA <-
  
  persistent_ASVs %>%
  
  filter(
    Pattern == "LJA"
  ) %>%
  
  mutate(
    
    Trajectory = paste(
      
      HubType_L,
      
      HubType_J,
      
      HubType_A,
      
      sep = " → "
      
    )
    
  )

pdf("Topological trayectories.pdf", width = 12)
ggplot(
  
  traj_df,
  
  aes(
    
    x = N,
    
    y = Trajectory,
    
    fill = Group
    
  )
  
)+
  
  geom_col(
    
    width = 0.72
    
  )+
  
  geom_text(
    
    aes(
      
      label = paste0(
        
        N,
        
        " (",
        
        scales::percent(
          N/sum(N),
          accuracy = 0.1
        ),
        
        ")"
        
      )
      
    ),
    
    hjust = -0.15,
    
    size = 4.5
    
  )+
  
  scale_fill_manual(
    
    values = c(
      
      "Always peripheral" = "grey78",
      
      "Degree-associated" = "#2C7FB8",
      
      "Betweenness-associated" = "#D95F02"
      
    )
    
  )+
  
  scale_x_continuous(
    
    expand = expansion(mult = c(0,0.12))
    
  )+
  
  labs(
    
    x = "Number of ASVs",
    
    y = NULL,
    
    fill = NULL
    
  )+
  
  theme_classic(base_size = 15)+
  
  theme(
    
    legend.position = "top",
    
    legend.justification = "center",
    
    legend.text = element_text(
      size = 12
    ),
    
    axis.text.y = element_text(
      size = 12
    ),
    
    axis.text.x = element_text(
      size = 12
    ),
    
    axis.title.x = element_text(
      size = 14,
      face = "bold"
    )
    
  )
dev.off()

persistent_larva <-
  
  alluvial_df %>%
  
  pull(Larva_ID)

length(persistent_larva)

persistent_juvenile <-
  
  alluvial_df %>%
  
  pull(Post_ID)

length(persistent_juvenile)

persistent_adult <-
  
  persistent_juvenile

write.table(
  
  data.frame(
    ID = persistent_larva
  ),
  
  "Persistent_Larva.txt",
  
  quote = FALSE,
  
  sep = "\t",
  
  row.names = FALSE
  
)

write.table(
  
  data.frame(
    ID = persistent_juvenile
  ),
  
  "Persistent_Juvenile.txt",
  
  quote = FALSE,
  
  sep = "\t",
  
  row.names = FALSE
  
)

write.table(
  
  data.frame(
    ID = persistent_adult
  ),
  
  "Persistent_Adult.txt",
  
  quote = FALSE,
  
  sep = "\t",
  
  row.names = FALSE
  
)



# ---- Figure 3: Conceptual model ---------------------------------------------

###Figura conceptual
## Stage 1 - Canvas
############################################################

library(ggplot2)
library(grid)

theme_set(
  theme_void(base_size = 15)
)

############################################################
## Canvas
############################################################

panelD <- ggplot() +
  
  coord_cartesian(
    xlim = c(0.3,3.55),
    ylim = c(-2.5,10),
    clip = "off"
  ) +
  
  ############################################################
## Development arrow
############################################################

geom_segment(
  
  aes(
    x = 1,
    xend = 3,
    y = 9.45,
    yend = 9.45
  ),
  
  linewidth = 0.7,
  
  arrow = arrow(
    length = unit(0.22,"cm"),
    type = "closed"
  )
  
) +
  
  ############################################################
## Development title
############################################################

annotate(
  
  "text",
  
  x = 2,
  
  y = 9.88,
  
  label = "Development",
  
  fontface = "bold",
  
  size = 6.2
  
) +
  
  ############################################################
## Developmental stages
############################################################

annotate(
  "text",
  x = 1,
  y = 8.75,
  label = "Tadpoles",
  fontface = "bold",
  size = 4.8
) +
  
  annotate(
    "text",
    x = 2,
    y = 8.75,
    label = "Juveniles",
    fontface = "bold",
    size = 4.8
  ) +
  
  annotate(
    "text",
    x = 3,
    y = 8.75,
    label = "Adults",
    fontface = "bold",
    size = 4.8
  ) +
  
  ############################################################
## Left labels
############################################################

annotate(
  
  "text",
  
  x = 0.48,
  
  y = 6.5,
  
  label = "Host\nfiltering",
  
  hjust = 1,
  
  fontface = "bold",
  
  size = 4
  
) +
  
  annotate(
    
    "text",
    
    x = 0.48,
    
    y = 4.0,
    
    label = "Network\nreorganization",
    
    hjust = 1,
    
    fontface = "bold",
    
    size = 4
    
  ) +
  
  annotate(
    
    "text",
    
    x = 0.48,
    
    y = 1.0,
    
    label = "Ontogenetic\npersistence",
    
    hjust = 1,
    
    fontface = "bold",
    
    size = 4
    
  )+
  
  
  
  ############################################################
## Theme
############################################################

theme(
  
  plot.margin =
    margin(
      15,
      30,
      15,
      65
    )
  
)

############################################################
## Community cloud
############################################################

make_cloud <- function(center_x,
                       center_y,
                       n,
                       radius_x,
                       radius_y){
  
  theta <- runif(n,0,2*pi)
  
  r <- sqrt(runif(n))
  
  data.frame(
    
    x = center_x + radius_x*r*cos(theta),
    
    y = center_y + radius_y*r*sin(theta),
    
    size = runif(
      n,
      2.4,
      4.2
    )
    
  )
  
}

############################################################
## Persistent genera
############################################################

persistent_genera <- c(
  
  "Pseudomonas",
  "Nocardioides",
  "Flavobacterium",
  "Chryseobacterium",
  "Hydrogenophaga"
  
)

persistent_paths <- data.frame(
  
  Genus = persistent_genera,
  
  Larvae_x = c(
    0.92,
    1.06,
    0.98,
    1.14,
    1.20
  ),
  
  Larvae_y = c(
    6.25,
    6.68,
    6.08,
    6.45,
    6.86
  ),
  
  Juvenile_x = c(
    1.93,
    2.07,
    1.98,
    2.12,
    2.17
  ),
  
  Juvenile_y = c(
    6.30,
    6.60,
    6.15,
    6.78,
    6.48
  ),
  
  Adult_x = c(
    2.90,
    3.05,
    2.98,
    3.10,
    3.16
  ),
  
  Adult_y = c(
    6.32,
    6.55,
    6.20,
    6.70,
    6.42
  )
  
)


############################################################
## Offset trajectories
############################################################

offset <- 0.035

persistent_paths$Larvae_x_out  <- persistent_paths$Larvae_x + offset
persistent_paths$Juvenile_x_in <- persistent_paths$Juvenile_x - offset

persistent_paths$Juvenile_x_out <- persistent_paths$Juvenile_x + offset
persistent_paths$Adult_x_in     <- persistent_paths$Adult_x - offset



############################################################
## Community
############################################################

set.seed(123)

larvae <- make_cloud(
  1,
  6.5,
  38,
  0.27,
  0.48
)

juvenile <- make_cloud(
  2,
  6.5,
  20,
  0.22,
  0.34
)

adult <- make_cloud(
  3,
  6.5,
  10,
  0.15,
  0.18
)

panelD <- panelD +
  
  geom_point(
    
    data=larvae,
    
    aes(
      x,
      y,
      size=size
    ),
    
    shape=21,
    
    fill="grey90",
    
    colour="grey45",
    
    stroke=.30,
    
    show.legend=FALSE
    
  )+
  
  geom_point(
    
    data=juvenile,
    
    aes(
      x,
      y,
      size=size
    ),
    
    shape=21,
    
    fill="grey90",
    
    colour="grey45",
    
    stroke=.30,
    
    show.legend=FALSE
    
  )+
  
  geom_point(
    
    data=adult,
    
    aes(
      x,
      y,
      size=size
    ),
    
    shape=21,
    
    fill="grey90",
    
    colour="grey45",
    
    stroke=.30,
    
    show.legend=FALSE
    
  )

############################################################
## Community filtering trajectories
############################################################

panelD <- panelD +
  
  geom_curve(
    
    data = persistent_paths,
    
    aes(
      x = Larvae_x_out,
      y = Larvae_y,
      xend = Juvenile_x_in,
      yend = Juvenile_y
    ),
    
    curvature = 0.10,
    
    linewidth = 0.25,
    
    linetype = "22",
    
    colour = "#D55E00",
    
    alpha = 0.70
    
  ) +
  
  geom_curve(
    
    data = persistent_paths,
    
    aes(
      x = Juvenile_x_out,
      y = Juvenile_y,
      xend = Adult_x_in,
      yend = Adult_y
    ),
    
    curvature = 0.10,
    
    linewidth = 0.25,
    
    linetype = "22",
    
    colour = "#D55E00",
    
    alpha = 0.70
    
  )

############################################################
## Persistent nodes (Community filtering)
############################################################

persistent_cloud <- data.frame(
  
  x = c(
    
    ## Cinco nodos principales
    persistent_paths$Larvae_x,
    
    ## Tres duplicados
    persistent_paths$Larvae_x[c(1,3,5)] + c(-0.035,0.040,-0.030),
    
    ## Juveniles
    persistent_paths$Juvenile_x,
    
    ## Adultos
    persistent_paths$Adult_x
    
  ),
  
  y = c(
    
    persistent_paths$Larvae_y,
    
    persistent_paths$Larvae_y[c(1,3,5)] + c(0.08,-0.07,0.06),
    
    persistent_paths$Juvenile_y,
    
    persistent_paths$Adult_y
    
  ),
  
  Stage = c(
    
    rep("Larvae",8),
    
    rep("Juveniles",5),
    
    rep("Adults",5)
    
  ),
  
  size = c(
    
    ## Larvas
    4.2,4.2,4.2,4.2,4.2,
    3.6,3.5,3.5,
    
    ## Juveniles
    rep(4.2,5),
    
    ## Adultos
    rep(4.2,5)
    
  )
  
)

panelD <- panelD +
  
  geom_point(
    
    data = persistent_cloud,
    
    aes(
      x,
      y,
      size = size
    ),
    
    shape = 21,
    
    fill = "#D55E00",
    
    colour = "black",
    
    stroke = 1.3,
    
    show.legend = FALSE
    
  )+
  
  scale_size_identity()

##########################################

         #Networks modularity
###################################
draw_network <- function(nodes,
                         edges,
                         persistent){
  
  list(
    
    geom_segment(
      data=edges,
      aes(x=x,
          y=y,
          xend=xend,
          yend=yend),
      linewidth=.45,
      colour="grey55"
    ),
    
    geom_point(
      
      data=nodes,
      
      aes(x,y,size=size),
      
      shape=21,
      
      fill="grey88",
      
      colour="grey35",
      
      stroke=.35
      
    ),
    
    geom_point(
      
      data=subset(nodes,persistent),
      
      aes(x,y),
      
      shape=21,
      
      size=4,
      
      fill="#D55E00",
      
      colour="black",
      
      stroke=1.3
      
    )
    
  )
  
}

############################################################
## Helper
############################################################

make_nodes <- function(x0,y0,coords){
  
  data.frame(
    
    id = seq_len(nrow(coords)),
    
    x = coords[,1] + x0,
    
    y = coords[,2] + y0
    
  )
  
}

############################################################
## LARVAE
############################################################

coords_larvae <- matrix(
  
  c(
    
    -0.20,  0.25,
    -0.05,  0.32,
    0.10,  0.28,
    0.24,  0.20,
    
    -0.18,  0.02,
    -0.02,  0.08,
    0.14,  0.02,
    0.28,  0.08,
    
    -0.15,-0.20,
    0.00,-0.28,
    0.18,-0.22,
    0.32,-0.12
    
  ),
  
  ncol=2,
  byrow=TRUE
  
)

nodes_larvae <-
  make_nodes(
    1,
    4,
    coords_larvae
  )

edges_larvae <- data.frame(
  
  from = c(
    1,2,3,
    5,6,7,
    9,10,
    
    1,2,3,4,
    5,6,7,8,
    
    2,3,
    6,7,
    5,6,7,8
  ),
  
  to = c(
    2,3,4,
    6,7,8,
    10,11,
    
    5,6,7,8,
    9,10,11,12,
    
    6,7,
    10,11,
    9,10,11,12
  )
  
)

############################################################
## JUVENILES
############################################################

coords_juvenile <- matrix(
  
  c(
    
    -0.18,0.22,
    -0.04,0.28,
    0.10,0.22,
    
    -0.18,-0.02,
    -0.02,0.04,
    0.12,-0.02,
    
    0.24,0.20,
    0.30,0.02,
    
    -0.02,-0.26,
    0.14,-0.22,
    
    0.30,-0.18,
    0.44,-0.02
    
  ),
  
  ncol=2,
  byrow=TRUE
  
)

nodes_juvenile <-
  make_nodes(
    2,
    4,
    coords_juvenile
  )

edges_juvenile <- data.frame(
  
  from=c(
    
    1,2,
    2,3,
    
    1,4,
    2,5,
    3,6,
    
    4,5,
    5,6,
    
    3,7,
    7,8,
    
    5,9,
    9,10,
    
    8,12,
    10,11
    
  ),
  
  to=c(
    
    2,3,
    
    4,5,6,
    
    5,6,
    
    7,8,
    
    9,10,
    
    12,11
    
  )
  
)

############################################################
## ADULTS
############################################################

coords_adult <- matrix(
  
  c(
    
    # Componente 1
    -0.35, 0.28,
    -0.20, 0.38,
    
    # Componente 2
    0.10, 0.24,
    0.28, 0.34,
    
    # Componente 3
    -0.32,-0.18,
    -0.15,-0.30,
    
    # Componente 4
    0.12,-0.12,
    0.30,-0.24,
    
    # Componente 5
    -0.02, 0.05,
    0.16,-0.02,
    
    # Componente 6
    0.52, 0.18,
    0.68, 0.02
    
  ),
  
  ncol = 2,
  byrow = TRUE
  
)

nodes_adult <-
  make_nodes(
    3,
    4,
    coords_adult
  )

edges_adult <- data.frame(
  
  from=c(
    
    1,3,5,7,9,11
    
  ),
  
  to=c(
    
    2,4,6,8,10,12
    
  )
  
)

###########################
      #persistentes
##########################
persistent_ids_larvae <- c(
  2,3,
  6,7,
  9,10,
  11,
  12
)

persistent_ids_juvenile <- c(
  2,5,7,8,10
)

persistent_ids_adult <- c(
  1,4,6,9,11
)

nodes_larvae$Persistent <-
  nodes_larvae$id %in%
  persistent_ids_larvae

nodes_juvenile$Persistent <-
  nodes_juvenile$id %in%
  persistent_ids_juvenile

nodes_adult$Persistent <-
  nodes_adult$id %in%
  persistent_ids_adult

###########################################################
## Node sizes
###########################################################

# Todos parten con el mismo tamaño
nodes_larvae$size <- 3.8
nodes_juvenile$size <- 3.8
nodes_adult$size <- 3.8

# Persistentes (Larvae)
nodes_larvae$size[nodes_larvae$Persistent] <-
  
  c(
    
    4.9,
    4.6,
    
    4.8,
    4.5,
    
    4.7,
    4.4,
    
    4.6,
    
    4.5
    
  )
# Persistentes (Juveniles)
nodes_juvenile$size[nodes_juvenile$Persistent] <-
  c(4.5,4.3,4.1,3.9,3.8)

# Persistentes (Adults)
nodes_adult$size[nodes_adult$Persistent] <-
  c(3.6,3.5,3.3,3.2,3.1)


draw_network <- function(nodes,
                         edges){
  
  list(
    
    geom_segment(
      
      data=merge(
        edges,
        nodes,
        by.x="from",
        by.y="id"
      ) |>
        merge(
          nodes,
          by.x="to",
          by.y="id",
          suffixes=c("","2")
        ),
      
      aes(
        
        x=x,
        
        y=y,
        
        xend=x2,
        
        yend=y2
        
      ),
      
      linewidth=.45,
      
      colour="grey60"
      
    ),
    
    geom_point(
      
      data = nodes,
      
      aes(
        x,
        y,
        size = size
      ),
      
      shape = 21,
      
      fill = "grey90",
      
      colour = "grey55",
      
      stroke = .30
      
    ),
    
    geom_point(
      
      data = subset(nodes, Persistent),
      
      aes(
        x,
        y,
        size = size
      ),
      
      shape = 21,
      
      fill = "#D55E00",
      
      colour = "black",
      
      stroke = 1.0
      
    ),
    scale_size_identity()
  )
  
}

nodes_larvae$size <- 3.8
nodes_larvae$size[nodes_larvae$Persistent] <- c(5.0,4.8,4.7,4.6,4.5)

nodes_juvenile$size <- 3.8
nodes_juvenile$size[nodes_juvenile$Persistent] <- c(4.5,4.3,4.1,3.9,3.8)

nodes_adult$size <- 3.8
nodes_adult$size[nodes_adult$Persistent] <- c(3.6,3.4,3.3,3.2,3.1)

panelD <- panelD +
  
  draw_network(
    nodes_larvae,
    edges_larvae
  ) +
  
  draw_network(
    nodes_juvenile,
    edges_juvenile
  ) +
  
  draw_network(
    nodes_adult,
    edges_adult
  )


#######################################

                #Trayectorias de persistentes
######################################

persistent_tracks <- data.frame(
  
  Genus = persistent_genera,
  
  x1 = c(0.93,1.06,0.99,1.13,1.19),
  y1 = c(6.26,6.67,6.08,6.47,6.86),
  
  x2 = c(1.95,2.05,1.98,2.12,2.18),
  y2 = c(6.30,6.61,6.12,6.74,6.48),
  
  x3 = c(2.90,3.04,2.98,3.10,3.16),
  y3 = c(6.31,6.55,6.22,6.69,6.42)
  
)

larvae_tracks <- subset(
  nodes_larvae,
  id %in% c(2,6,9,11,12)
)

juvenile_persist <- subset(
  nodes_juvenile,
  Persistent
)

adult_persist <- subset(
  nodes_adult,
  Persistent
)

larvae_tracks$Genus <- persistent_genera
juvenile_persist$Genus <- persistent_genera
adult_persist$Genus <- persistent_genera

tracks <-
  
  larvae_tracks |>
  
  merge(
    
    juvenile_persist,
    
    by="Genus",
    
    suffixes=c("_L","_J")
    
  ) |>
  
  merge(
    
    adult_persist,
    
    by="Genus"
    
  )

offset_net <- 0.035

tracks$xL_out <- tracks$x_L + offset_net
tracks$xJ_in  <- tracks$x_J - offset_net

tracks$xJ_out <- tracks$x_J + offset_net
tracks$xA_in  <- tracks$x - offset_net

panelD <-
  
  panelD +
  
  geom_curve(
    
    data=tracks,
    
    aes(
      
      x=xL_out,
      
      y=y_L,
      
      xend=xJ_in,
      
      yend=y_J
      
    ),
    
    curvature=0.18,
    
    linewidth=0.20,
    linetype = "dashed",
    
    colour="#D55E00",
    
    alpha=0.70
    
  )+
  
  geom_curve(
    
    data=tracks,
    
    aes(
      
      x=xJ_out,
      
      y=y_J,
      
      xend=xA_in,
      
      yend=y
      
    ),
    
    curvature=0.18,
    
    linewidth=0.20,
    linetype = "dashed",
    
    colour="#D55E00",
    
    alpha=0.70
    
  )

#######Bloque de persistencia ontogenética###################
traj_draw <- tribble(
  
  ~Trajectory,             ~Stage,      ~Role,
  
  "Peripheral",            "Tadpole",   "None",
  "Peripheral",            "Juvenile",  "None",
  "Peripheral",            "Adult",     "None",
  
  "Degree_early",          "Tadpole",   "Degree",
  "Degree_early",          "Juvenile",  "None",
  "Degree_early",          "Adult",     "None",
  
  "Degree_late",           "Tadpole",   "None",
  "Degree_late",           "Juvenile",  "None",
  "Degree_late",           "Adult",     "Degree",
  
  "BTW_early",             "Tadpole",   "BTW",
  "BTW_early",             "Juvenile",  "None",
  "BTW_early",             "Adult",     "None",
  
  "BTW_middle",            "Tadpole",   "None",
  "BTW_middle",            "Juvenile",  "BTW",
  "BTW_middle",            "Adult",     "None",
  
  "BTW_late",              "Tadpole",   "None",
  "BTW_late",              "Juvenile",  "None",
  "BTW_late",              "Adult",     "BTW",
  
  "BTW_persistent",        "Tadpole",   "None",
  "BTW_persistent",        "Juvenile",  "BTW",
  "BTW_persistent",        "Adult",     "BTW"
  
)

traj_draw <-
  
  traj_draw %>%
  
  mutate(
    
    x = case_when(
      
      Stage=="Tadpole" ~ 1,
      
      Stage=="Juvenile" ~ 2,
      
      TRUE ~ 3
      
    ),
    
    y = case_when(
      
      Trajectory=="Peripheral" ~ 0.6,
      
      Trajectory=="Degree_early" ~ 0.2,
      
      Trajectory=="Degree_late" ~ -0.2,
      
      Trajectory=="BTW_early" ~ -0.6,
      
      Trajectory=="BTW_middle" ~ -1.0,
      
      Trajectory=="BTW_late" ~ -1.4,
      
      Trajectory=="BTW_persistent" ~ -1.8,
      
      TRUE ~ 7
      
    )
    
  )

traj_draw <-
  
  traj_draw %>%
  
  mutate(
    
    size = case_when(
      
      Role=="None" ~ 2.8,
      
      Role=="Degree" ~ 5,
      
      Role=="BTW" ~ 5
      
    )
    
  )


traj_draw <-
  
  traj_draw %>%
  
  mutate(
    
    fill = case_when(
      
      Role=="None" ~ "grey92",
      
      Role=="Degree" ~ "#D55E00",
      
      Role=="BTW" ~ "#D55E00"
      
    )
    
  )

panelD = panelD + geom_path(
  
  data = traj_draw,
  
  aes(
    
    x,
    
    y,
    
    group=Trajectory
    
  ),
  
  colour="#D55E00",
  
  linewidth=.45,
  
  linetype=2
  
)+
  geom_point(
  
  data=traj_draw,
  
  aes(
    
    x,
    
    y,
    
    size=size
    
  ),
  
  shape=21,
  
  fill=traj_draw$fill,
  
  colour="black",
  
  stroke=.6
  
)+
  scale_size_identity()


pdf("PanelD.pdf")
panelD
dev.off()


# Save main figures using the same objects produced above. Adjust device options
# here if journal-specific dimensions are required.
#
# ggsave(file.path(FIGURES_DIR, "Fig1.pdf"), ...)
# ggsave(file.path(FIGURES_DIR, "Fig2.pdf"), ...)
# ggsave(file.path(FIGURES_DIR, "Fig3.pdf"), ...)
#
# The original analysis script used several intermediate plot objects and PDF
# devices. Those exports are intentionally not executed automatically in this
# first refactor; final journal-ready export settings can be centralized here.
